workflows:
  ios-testflight:
    name: iOS TestFlight Build
    working_directory: ios-build/ios
    integrations:
      app_store_connect: Codemagic
    environment:
      groups:
        - app_store_credentials
      vars:
        XCODE_PROJECT: "Next-Steps.xcodeproj"
        XCODE_SCHEME: "Next-Steps"
    scripts:
      - name: Build and Sign iOS
        script: |
          xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
    publishing:
      app_store_connect:
        auth: integration
